@startuml
entity User {
    * id: string <<generated>>
    --
    username: string
    password: string
    isEnabled: boolean
}

entity Authority {
    * id: string <<generated>>
    user_id: string <<FK>>
    --
    authority: string
}

entity Group {
    * id: string <<generated>
    --
    group_name: string
}

entity GroupAuthority {
    * group_id: string <<FK>>
    --
    authority: string
}

entity GroupMembers {
    * id: string <<generated>>
    --
    user_id: string
    group_id: string
}

entity Department {
    id: string <<generated>>
    user_id: string <<FK>>
    --
    name: string
}

entity Item {
    * id: string <<generated>>
    department_id: string <<FK>>
    user_request_by: string <<FK>>
    --
    status: string
    name: string
    price: string
}

entity ItemApproval {
    id: string <<generated>>
    approved_by: string <<FK>>
    --
    level: number
}

entity DepartmentApproval {
    department_id: string <<FK>>
    user_id: string <<FK>>
    item_id: string
    --
}

User ||--|{ Authority
User ||--|{ Department
User ||--|{ Item

Group ||--|{ GroupAuthority
Group ||--|{ GroupMembers

Department ||--|{ DepartmentApproval
DepartmentApproval ||--|{ Item

Item ||--|| ItemApproval
ItemApproval ||--|| User

@enduml
