@startuml
'https://www.coderbased.com/p/multi-level-approval-system-design'

scale 0.7
entity User {
    * id: string <<generated>>
    --
    username: string
    password: string
    fullname: string
    position: string
    isEnabled: boolean
}

entity Authority {
    * id: string <<generated>>
    user_id: string <<FK>>
    --
    authority: string
}

entity Group {
    * id: string <<generated>
    --
    group_name: string
}

entity GroupAuthority {
    * group_id: string <<FK>>
    --
    authority: string
}

entity GroupMembers {
    * id: string <<generated>>
    --
    user_id: string
    group_id: string
}

entity Department {
    id: string <<generated>>
    user_id: string <<FK>>
    --
    name: string
}

entity Item {
    * id: string <<generated>>
    department_id: string <<FK>>
    user_request_by: string <<FK>>
    --
    name: string
    price: number
    qty: number
}

entity ApprovalWorkflow {
    * id: string <<generated>>
    --
    min: number
    max: number
    weight: number
}

entity ApprovalWorkflowUser {
    * id: string <<generated>>
    --
    workflow_id: string
    user_id: string
}

entity ApprovalWorkflowStage {
    * id: string <<generated>>
    workflow_id: string <<FK>>
    ---
    level: number
    approver_type: ApproverType
    approver_ids: text[]
    approve_count: number,
    approve_superior_level: number
    created_at: Datetime,
    updated_at: Datetime
}

entity ApprovalTransaction {
    * id: string <<generated>>
    item_id: string <<FK>>
    workflow_id: string <<FK>>
    workflow_stage_id: string <<FK>>
    --
    level: number
    approver: text[]
    approve_count: number
    status: ApprovalStatus
    created_at: Datetime
    updated_at: Datetime
}

enum ApproverType {
    SUPERIOR
    EMPLOYEE
}

enum ApprovalStatus {
    PENDING
    WAITING
    APPROVED
    REJECT
}



User ||--|{ Authority
User ||--|{ Department
User ||--|{ Item

Group ||--|{ GroupAuthority
Group ||--|{ GroupMembers

ApprovalWorkflow ||--|{ ApprovalWorkflowUser
ApprovalWorkflowUser ||--|{ ApprovalWorkflowStage
ApprovalWorkflowStage ||--|{ ApprovalTransaction
Item ||--|{ ApprovalTransaction
ApprovalWorkflow ||--|{ ApprovalTransaction


@enduml
